debug=true

spring.application.name=fg_mcp_server_integration_tests

spring.ai.mcp.client.name=fg_mcp_server_integration_tests
spring.ai.mcp.client.stdio.connections.fg_mcp_server_integration_tests.command=/opt/homebrew/bin/jbang
spring.ai.mcp.client.stdio.connections.fg_mcp_server_integration_tests.args=run,--java=25,../fg_mcp_server/target/fg_mcp_server-0.2.0-SNAPSHOT.jar
