<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>io.github.rmcdouga.fgumcpserver</groupId>
	<artifactId>fg_mcp_server</artifactId>
	<version>0.1.0</version>
	<name>fg_mcp_server</name>
	<description>Fantasy Grounds MCP Server</description>
	<url>https://github.com/rmcdouga/FGU_MCP_Server</url>
	<inceptionYear>2026</inceptionYear>

	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>

	<organization>
		<name>Rob McDougall</name>
		<url>https://github.com/rmcdouga</url>
	</organization>

	<developers>
		<developer>
		    <id>rmcdouga</id>
			<name>Rob McDougall</name>
			<email>rmcdouga@gmail.com</email>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/rmcdouga/FGU_MCP_Server.git</connection>
		<developerConnection>scm:git:https://github.com/rmcdouga/FGU_MCP_Server.git</developerConnection>
		<url>https://github.com/rmcdouga/FGU_MCP_Server</url>
		<tag/>
	</scm>

	<properties>
		<java.version>25</java.version>
		<spring-ai.version>2.0.1</spring-ai.version>
		<spring-modulith.version>2.1.1</spring-modulith.version>
		<jreleaser-plugin.version>1.26.0</jreleaser-plugin.version>
	</properties>

	<distributionManagement>
		<snapshotRepository>
			<id>github</id>
			<name>GitHub Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/rmcdouga/FGU_MCP_Server</url>
		</snapshotRepository>
		<repository>
			<id>github</id>
			<name>GitHub Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/rmcdouga/FGU_MCP_Server</url>
		</repository>
	</distributionManagement>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-mcp-server-webmvc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.modulith</groupId>
			<artifactId>spring-modulith-starter-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.modulith</groupId>
			<artifactId>spring-modulith-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-mcp-client</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.modulith</groupId>
				<artifactId>spring-modulith-bom</artifactId>
				<version>${spring-modulith.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<profiles>
	    <profile>
			<!-- Profile for creating a "full" release for publication (with signed versions of sources and javadocs) -->
	        <id>publication</id>
 			<properties>
        	   	<altDeploymentRepository>local::file:${project.build.directory}/staging-deploy</altDeploymentRepository>
            </properties>
            <build>
	            <plugins>
	                <plugin>
	                    <groupId>org.apache.maven.plugins</groupId>
	                    <artifactId>maven-javadoc-plugin</artifactId>
	                    <executions>
	                        <execution>
	                            <id>attach-javadocs</id>
	                            <goals>
	                                <goal>jar</goal>
	                            </goals>
	                            <configuration>
	                                <attach>true</attach>
	                            </configuration>
	                        </execution>
	                    </executions>
	                </plugin>
	                <plugin>
	                    <groupId>org.apache.maven.plugins</groupId>
	                    <artifactId>maven-source-plugin</artifactId>
	                    <executions>
	                        <execution>
	                            <id>attach-sources</id>
	                            <goals>
	                                <goal>jar</goal>
	                            </goals>
	                            <configuration>
	                                <attach>true</attach>
	                            </configuration>
	                        </execution>
	                    </executions>
	                </plugin>
	            </plugins>
	        </build>
	    </profile>
		<profile>
			<!-- Profile for releasing code to Maven Central -->
			<id>release</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jreleaser</groupId>
						<artifactId>jreleaser-maven-plugin</artifactId>
						<version>${jreleaser-plugin.version}</version>
						<inherited>false</inherited>
						<configuration>
							<gitRootSearch>true</gitRootSearch>
							<dryrun>false</dryrun>
							<jreleaser>
								<release>
									<github>
										<owner>rmcdouga</owner>
										<overwrite>true</overwrite>
									</github>
								</release>
								<files>
									<globs>
										<glob>
											<pattern>${project.build.directory}/staging-deploy/**/${project.artifactId}-${project.version}*.*</pattern>
										</glob>
									</globs>
								</files>
								<signing>
									<pgp>
										<active>ALWAYS</active>
										<armored>true</armored>
									</pgp>
								</signing>
								<deploy>
									<maven>
										<mavenCentral>
											<release-deploy>
												<active>RELEASE</active>
												<applyMavenCentralRules>true</applyMavenCentralRules>
												<url>https://central.sonatype.com/api/v1/publisher</url>
												<stagingRepositories>${project.build.directory}/staging-deploy</stagingRepositories>
											</release-deploy>
										</mavenCentral>
									</maven>
								</deploy>
							</jreleaser>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
