<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>io.github.rmcdouga.fgmcpserver_integ_tests</groupId>
	<artifactId>fg_mcp_server_integration_tests</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>fg_mcp_server_integration_tests</name>
	<description>Fantasy Grounds MCP Server integration tests</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>25</java.version>
		<spring-ai.version>2.0.1</spring-ai.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-mcp-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-client-chat</artifactId>
		</dependency>
		<dependency>
			<groupId>org.modeljars</groupId>
			<artifactId>modeljars</artifactId>
			<version>0.1.31</version>
		</dependency>
		<dependency>
			<groupId>com.integrallis</groupId>
			<artifactId>models-spring-ai</artifactId>
			<version>0.3.26</version>
		</dependency>
		<dependency>
			<groupId>org.modeljars.huggingface</groupId>
			<artifactId>qwen.qwen3-1.7b-gguf.q8_0</artifactId>
			<version>3.0.0-q8_0.2</version>
		</dependency>
		<!--
		<dependency>
			<groupId>org.modeljars.huggingface</groupId>
			<artifactId>cactus-compute.needle2-cact.cq2_mixed</artifactId>
			<version>2.0.0-cq2_mixed.2</version>
		</dependency>
		-->
		<!--
		<dependency>
			<groupId>org.modeljars.huggingface</groupId>
			<artifactId>qwen.qwen3-8b-gguf.q4_k_m</artifactId>
			<version>3.0.0-q4_k_m.2</version>
		</dependency>
		-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
